### ISSUE TITLE
Flow Issues on Mobile Devices

### ISSUE THREAD

**Issue by Pliavi** [deeplibras/deeplibras.github.io#12]
**Apoio:**
![apoio](https://cloud.githubusercontent.com/assets/5985423/19853286/6b1994a6-9f4f-11e6-8d52-e8d719b2bb49.png)
_Under 912 px (Tested on GoogleChrome Tools)_

The prefecture logo goes down due the width of IFSP logo, it can be fixed starting the vertical flowing(change flex orientation to column) on 800px or 768px (and will help with the other problem below).

**Text Overlapping and Breaking**
![all](https://cloud.githubusercontent.com/assets/5985423/19853328/b001bf9e-9f4f-11e6-8c2b-b3764aa664ba.png)
_Under 633 px (Tested on a Real Smartphone)_

Due the text on pseudo-element `:before` with absolute position, all of titles goes to the same `top: 0`, a possibly solution (after column orientation) is remove `top: 0`, use the `margin-top` instead (fixed value if all images have the same height %, else not), and use `left` with % to adapt the text position.

**Example:**
![soluc](https://cloud.githubusercontent.com/assets/5985423/19853718/2131524a-9f52-11e6-81b7-a9b6570c3c3b.png)
_IFSP logo should be resized too, it's getting bigger than the screensize (red square)_

Or, remove the use of `:before` and make the titles with a new `div` tag (I think it's more "problem avoider").

And to finish, the footer _copyrigths/"ultima atualização"_ is breaking the `div` space (due the floating on "ultima atualização" `span`) on resizing, it would be resolved with another column orientarion (or maybe clearing the `float`) and centering the texts.

Edit:
------
Maybe all the problems area solved using media-queries, so, take care with the minimum resolutions (strict or by larger device proximity).

**Comment by Pliavi** [comment]
There's another flow problem, on ECSL event pages ([I ECSL](http://deeplibras.github.io/pt/ecsl/#201601) and [II ECSL](http://deeplibras.github.io/pt/ecsl/#201602)), the `.session` classes are `inline-block` and have `flex:1` without an alternative to smaller screens, each session are a column, so even in smaller screens they share the same space, and they are three (on a 400px screen it's less than 150px to each column). They could come one below other.
**A Tip:** The same can be used on the main event page, to push the gallery below the events.

And another observation is that there's no `wordcloud.js` file on `js` folder
(there's one `wordcloud2.js` in `images/person` folder), but it's requested in the `index.html` file (404 on console).

**Comment by lucasvenez** [comment]
@Pliavi, thank you very much for your attention and suggestions!
